# Generated by Django 6.0.8 on 2026-09-07 20:18

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commerce", "0002_workspaceaccess"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "activity",
                "verbose_name_plural": "Activities",
            },
        ),
        migrations.AlterModelOptions(
            name="contact",
            options={
                "ordering": ("-is_primary", "name"),
                "verbose_name": "contact",
                "verbose_name_plural": "contacts",
            },
        ),
        migrations.AlterModelOptions(
            name="customer",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "customer",
                "verbose_name_plural": "customers",
            },
        ),
        migrations.AlterModelOptions(
            name="invoice",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "invoice",
                "verbose_name_plural": "invoices",
            },
        ),
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "order",
                "verbose_name_plural": "orders",
            },
        ),
        migrations.AlterModelOptions(
            name="organization",
            options={
                "ordering": ("name",),
                "verbose_name": "organization",
                "verbose_name_plural": "organizations",
            },
        ),
        migrations.AlterModelOptions(
            name="payment",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "payment",
                "verbose_name_plural": "payments",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ("name",),
                "verbose_name": "product",
                "verbose_name_plural": "products",
            },
        ),
        migrations.AlterField(
            model_name="activity",
            name="actor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="actor",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="activity",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="commerce.customer",
                verbose_name="customer",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, verbose_name="metadata"),
        ),
        migrations.AlterField(
            model_name="activity",
            name="summary",
            field=models.CharField(max_length=255, verbose_name="summary"),
        ),
        migrations.AlterField(
            model_name="activity",
            name="verb",
            field=models.CharField(max_length=100, verbose_name="verb"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="commerce.customer",
                verbose_name="customer",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="email"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="is_primary",
            field=models.BooleanField(default=False, verbose_name="is primary"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="name",
            field=models.CharField(max_length=180, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="role",
            field=models.CharField(blank=True, max_length=120, verbose_name="role"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="email"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="lifetime_value",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=12, verbose_name="lifetime value"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(max_length=180, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="notes",
            field=models.TextField(blank=True, verbose_name="notes"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customers",
                to="commerce.organization",
                verbose_name="organization",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_customers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="owner",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(blank=True, max_length=40, verbose_name="phone"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="status",
            field=models.CharField(
                choices=[
                    ("lead", "Lead"),
                    ("active", "Active"),
                    ("at_risk", "At risk"),
                    ("inactive", "Inactive"),
                ],
                default="lead",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="commerce.customer",
                verbose_name="customer",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="due_date",
            field=models.DateField(verbose_name="due date"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="issued_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="issued at"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="number",
            field=models.CharField(max_length=30, unique=True, verbose_name="number"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="commerce.order",
                verbose_name="order",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("open", "Open"),
                    ("paid", "Paid"),
                    ("void", "Void"),
                    ("overdue", "Overdue"),
                ],
                default="draft",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="total",
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name="total"),
        ),
        migrations.AlterField(
            model_name="order",
            name="cancellation_reason",
            field=models.TextField(blank=True, verbose_name="cancellation reason"),
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="order",
            name="currency",
            field=models.CharField(default="USD", max_length=3, verbose_name="currency"),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="commerce.customer",
                verbose_name="customer",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="expected_at",
            field=models.DateField(blank=True, null=True, verbose_name="expected at"),
        ),
        migrations.AlterField(
            model_name="order",
            name="internal_note",
            field=models.TextField(blank=True, verbose_name="internal note"),
        ),
        migrations.AlterField(
            model_name="order",
            name="placed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="placed at"),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("processing", "Processing"),
                    ("shipped", "Shipped"),
                    ("cancelled", "Cancelled"),
                    ("refunded", "Refunded"),
                ],
                default="draft",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name="subtotal"),
        ),
        migrations.AlterField(
            model_name="order",
            name="tax",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=12, verbose_name="tax"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total",
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name="total"),
        ),
        migrations.AlterField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="domain",
            field=models.CharField(blank=True, max_length=180, verbose_name="domain"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="employee_count",
            field=models.PositiveIntegerField(default=0, verbose_name="employee count"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="industry",
            field=models.CharField(blank=True, max_length=100, verbose_name="industry"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.CharField(max_length=180, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="website",
            field=models.URLField(blank=True, verbose_name="website"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name="amount"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="commerce.invoice",
                verbose_name="invoice",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="processed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="processed at"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="reference",
            field=models.CharField(max_length=60, unique=True, verbose_name="reference"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("succeeded", "Succeeded"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                ],
                default="pending",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=180, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(max_length=40, unique=True, verbose_name="sku"),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("draft", "Draft"), ("retired", "Retired")],
                default="draft",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(default=0, verbose_name="stock"),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name="unit price"),
        ),
    ]
