# Generated by Django 6.0.8 on 2026-09-08 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modern_admin", "0003_rename_audit_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductTourState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("site_name", models.CharField(max_length=100)),
                (
                    "outcome",
                    models.CharField(
                        choices=[("completed", "Completed"), ("dismissed", "Dismissed")],
                        max_length=10,
                    ),
                ),
                ("finished_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modern_admin_product_tours",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "site_name"), name="modern_admin_unique_product_tour"
                    )
                ],
            },
        ),
    ]
